site_name: Quality measure and cohort service    

theme: material

copyright: 'Copyright &copy; 2020 IBM Watson Health<br>'

repo_name: 'Quality measure and cohort service'
repo_url: https://github.com/festewart/quality-measure-and-cohort-service

edit_uri: https://github.com/festewart/quality-measure-and-cohort-service/tree/master/docs/

#Page tree

nav:
  - Installation: 
    - Instructions: installation/instructions.md
  - User Guide:
    - Getting Started: user-guide/getting-started.md
  - Developer Guide:
    - Getting Started: dev-guide/getting-started.md
    - Open Source: dev-guide/open-source.md
    - Artifactory and TaaS: dev-guide/artifactory-and-taas.md
    - Maven: dev-guide/maven.md
    - Spikes:
      - cql_engine audit: dev-guide/spikes/cql-engine-audit.md

#  - UBI Images:
#    - Overview: base_images.md
#  - Docker files: docker.md
#  - Helm charts: helm.md
#  - Operators: operators.md
#  - CI/CD: cicd.md

extra_javascript:
  - js/links_in_new_tabs.js
markdown_extensions:
  - admonition:
  - codehilite:
  - extra:
  - pymdownx.magiclink:
  - sane_lists:
  - smarty:
  - toc:
      permalink: True

# Plugins
plugins:
    - search
    - markdownextradata:
        data: ./docs/data
