name: Build and publish docs
on:
  push:
    branches:
      - master
jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pip3 install mkdocs mkdocs-material
      - run: pip3 install pymdown-extensions
      - run: pip3 install mkdocs-markdownextradata-plugin
      - run: mkdocs build --verbose --clean --strict
      - run: mkdocs gh-deploy
