name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pip install mkdocs mkdocs-material
      - run: pip install mkdocs pymdown-extensions
      - run: pip install mkdocs mkdocs-markdownextradata-plugin
      - run: mkdocs build --verbose --clean --strict
      - run: mkdocs gh-deploy
